name: qh test
on:
  workflow_dispatch:

jobs:
  showWithMirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
        env:
          ACTIONS_RUNNER_DEBUG: true
      - name: Show Origin Repos
        run: |
          echo "host: ${{ secrets.HOST }}"
          echo "touch file" && echo ${{ secrets.HOST }} >> ./${{ secrets.HOST }}
          echo "cat file content" && cat ./${{ secrets.HOST }}
          echo "ping host"
          ping -c 3 ${{ secrets.HOST }}
          ./gradlew showRepos
      - name: Show Repos After Clearing
        run: |
          ./gradlew showRepos -I init.gradle



